name: github pages
on:
  workflow_dispatch:
    branches:
      - main 
  push:
    branches:
      - main

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: "main"
            submodules: true
            fetch-depth: 1

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.7

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Build
          run: |
            make html

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build/html
